spring.application.name=devflow

spring.datasource.url=jdbc:postgresql://localhost:5432/devflow
spring.datasource.username=otmanedyaf
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=devflow-super-secret-key-change-this-later-123456789
jwt.expiration=86400000
